### PR TITLE
Fixes issues #18 and #19 with Z pie eating key inputs

### LINKED ISSUE #18: Z shortcut is active in 2D, script editor, etc
That's the only one I notice but you should check your code thoroughly.

Other than that, love it!

### PR DESCRIPTION
**Pull request by tmilker**
This fix incorporates some of @dc1248's changes mentioned in the comments of #18.  However, their fixes alone did not solve the issue because the letter z input was still being consumed when the focus wasn't in the 3D view(like in the Groups' text input field).  This takes a new approach to determine if the 3D viewport has focus and only trigger then, correcting both #18 and partially corrects #19.

This pull request does not address the 2nd item of #19 where the pie is still active but invisible upon a second keypress.

Fix #18 
- [x] Disable pie menu in any tab other than 3D #18 
- [x] Press Z outside 3D viewport prints error message #19

### CODE REVIEW

**Comment by imjp94** [comment]
Thanks for the effort!
Let me know if you want to include the fix for "invisible pie menu", otherwise it is good to go.

**Comment by tmilker** [comment]
@imjp94 I don't think I'm going to try tackling the pie issue at this time.  Maybe that one could be broken out into a new issue.

**Comment by imjp94** [comment]
Gotcha, thank you!

**Comment by dc1248** [comment]
Thanks @tmilker !

As for #19 I'll test it again now that Godot 4.2 is out, and maybe I'll take another stab at the unsolved parts. It would really to nice to make the pie menu mouse/keyboard UI work exactly like Blender's if possible in Godot.

**Pull request merged**
